<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAP-KARTHIGA" failures="1" tests="8" name="Surefire test" time="145.49" errors="0" timestamp="20 Sep 2023 02:35:31 GMT">
  <testcase classname="KarthigaAcademy.testcomponents.BaseTest" name="@BeforeMethod lanchApplication" time="10.636">
    <failure type="org.openqa.selenium.remote.UnreachableBrowserException" message="Error communicating with the remote browser. It may have died.
Build info: version: &amp;apos;4.11.0&amp;apos;, revision: &amp;apos;040bc5406b&amp;apos;
System info: os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;11.0.14&amp;apos;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [d1d7f0a8a61c8345ca31b7f05bfe9566, get [url]]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 117.0.2045.31, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:59189}, msedge: {msedgedriverVersion: 117.0.2045.31 (fdd954ad1e8c..., userDataDir: C:\Users\VISHAKAN\AppData\L...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:59189/devtoo..., se:cdpVersion: 117.0.2045.31, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d1d7f0a8a61c8345ca31b7f05bfe9566">
      <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.14'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [d1d7f0a8a61c8345ca31b7f05bfe9566, get [url]]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 117.0.2045.31, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:59189}, msedge: {msedgedriverVersion: 117.0.2045.31 (fdd954ad1e8c..., userDataDir: C:\Users\VISHAKAN\AppData\L...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:59189/devtoo..., se:cdpVersion: 117.0.2045.31, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d1d7f0a8a61c8345ca31b7f05bfe9566
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:300)
	at karthigaacademy.pageobjects.LandingPage.goInto(LandingPage.java:51)
	at KarthigaAcademy.testcomponents.BaseTest.lanchApplication(BaseTest.java:86)
Caused by: java.io.UncheckedIOException: java.io.IOException: An existing connection was forcibly closed by the remote host
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:96)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:188)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	... 35 more
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod lanchApplication -->
  <testcase classname="KarthigaAcademy.product.ErrorMessageValidationTest" name="productErrorValidation" time="3.638">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="KarthigaAcademy.product.ErrorMessageValidationTest" name="productErrorValidation" time="3.329"/>
  <testcase classname="KarthigaAcademy.product.ErrorMessageValidationTest" name="submitOrder" time="12.307">
    <skipped/>
  </testcase> <!-- submitOrder -->
  <testcase classname="KarthigaAcademy.product.ErrorMessageValidationTest" name="submitOrder" time="2.382">
    <skipped/>
  </testcase> <!-- submitOrder -->
  <testcase classname="KarthigaAcademy.product.ErrorMessageValidationTest" name="submitOrder" time="0.866">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.] but found [Incorrect emai or password.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect emai or password.]
	at KarthigaAcademy.product.ErrorMessageValidationTest.submitOrder(ErrorMessageValidationTest.java:22)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="KarthigaAcademy.product.StandAloneTest" name="submitOrderForSelectedProduct" time="7.436"/>
  <testcase classname="KarthigaAcademy.product.StandAloneTest" name="submitOrderForSelectedProduct" time="6.58"/>
  <testcase classname="KarthigaAcademy.product.StandAloneTest" name="OrderHistory" time="0.0">
    <skipped/>
  </testcase> <!-- OrderHistory -->
</testsuite> <!-- Surefire test -->
